def string_methods(s):
    print(f"🔹 Original String: '{s}'\n")

    print("upper():", s.upper())
    print("lower():", s.lower())
    print("capitalize():", s.capitalize())
    print("title():", s.title())
    print("swapcase():", s.swapcase())
    print("strip():", s.strip())
    print("lstrip():", s.lstrip())
    print("rstrip():", s.rstrip())
    print("replace('a', '@'):", s.replace('a', '@'))
    print("count('a'):", s.count('a'))
    print("startswith('a'):", s.startswith('a'))
    print("endswith('a'):", s.endswith('a'))
    print("find('a'):", s.find('a'))
    print("rfind('a'):", s.rfind('a'))
    print("index('a'):", s.index('a') if 'a' in s else "Not Found")
    print("rindex('a'):", s.rindex('a') if 'a' in s else "Not Found")
    print("split():", s.split())
    print("split('a'):", s.split('a'))
    print("rsplit('a'):", s.rsplit('a'))
    print("partition('a'):", s.partition('a'))
    print("rpartition('a'):", s.rpartition('a'))
    print("center(20, '*'):", s.center(20, '*'))
    print("ljust(20, '-'):", s.ljust(20, '-'))
    print("rjust(20, '-'):", s.rjust(20, '-'))
    print("zfill(20):", s.zfill(20))
    print("isalnum():", s.isalnum())
    print("isalpha():", s.isalpha())
    print("isdigit():", s.isdigit())
    print("islower():", s.islower())
    print("isupper():", s.isupper())
    print("istitle():", s.istitle())
    print("isspace():", s.isspace())
    print("join('!'):", '!'.join(s))
    print("encode():", s.encode())
    print("expandtabs(4):", s.expandtabs(4))
    print("casefold():", s.casefold())
string_methods("  pedram  ")
